In [4]:
import pandas as pd

In [10]:
movies = pd.read_csv('DataSets/movies.csv')
movies.head(10)

,movie_id,title,content_type,genre_primary,genre_secondary,release_year,duration_minutes,rating,language,country_of_origin,imdb_rating,production_budget,box_office_revenue,number_of_seasons,number_of_episodes,is_netflix_original,added_to_platform,content_warning
0,movie_0001,Dragon Legend,Stand-up Comedy,History,Thriller,2014,35.0,TV-Y,French,Japan,NaN,NaN,NaN,NaN,NaN,False,2023-08-07,False
1,movie_0002,Storm Warrior,Stand-up Comedy,Sci-Fi,NaN,2017,37.0,PG,Japanese,USA,3.3,NaN,NaN,NaN,NaN,False,2022-01-28,True
2,movie_0003,Fire Family,Movie,Drama,NaN,2003,142.0,TV-MA,English,USA,8.5,2114120.0,NaN,NaN,NaN,False,2021-05-04,True
3,movie_0004,Our Princess,Documentary,Sci-Fi,NaN,2011,131.0,NC-17,Japanese,USA,5.3,NaN,NaN,NaN,NaN,False,2022-11-26,False
4,movie_0005,Warrior Mission,Documentary,Sport,Mystery,2015,91.0,TV-G,English,USA,3.1,NaN,NaN,NaN,NaN,False,2023-06-15,False
5,movie_0006,Kingdom Phoenix,Movie,Documentary,Music,1997,113.0,PG-13,English,USA,8.0,4214426.0,792291.0,NaN,NaN,False,2021-01-21,False
6,movie_0007,Battle Story,TV Series,Sci-Fi,NaN,2003,52.0,TV-Y7,English,USA,NaN,NaN,NaN,NaN,158.0,False,2021-11-30,False
7,movie_0008,Old House,Movie,Horror,NaN,1991,109.0,TV-Y,Spanish,South Korea,7.7,629216.0,3995303.0,NaN,NaN,False,2020-10-04,False
8,movie_0009,Dragon Empire,Movie,Biography,NaN,2013,123.0,PG,Spanish,USA,8.4,NaN,NaN,NaN,NaN,False,2024-05-09,False
9,movie_0010,Dream War,Limited Series,Thriller,Animation,2019,49.0,TV-Y,Italian,Japan,8.2,NaN,NaN,12.0,32.0,False,2021-09-20,False

In [13]:
recommendation_logs = pd.read_csv('DataSets/recommendation_logs.csv')
recommendation_logs.head(10)

,recommendation_id,user_id,movie_id,recommendation_date,recommendation_type,recommendation_score,was_clicked,position_in_list,device_type,time_of_day,algorithm_version
0,rec_000001,user_06326,movie_0771,2025-07-03,new_releases,NaN,False,10,Tablet,evening,v1.4
1,rec_000002,user_02180,movie_0985,2024-11-07,genre_based,0.916,False,9,Mobile,evening,v1.4
2,rec_000003,user_03535,movie_0834,2024-08-22,personalized,0.816,False,2,Tablet,evening,v1.4
3,rec_000004,user_05025,movie_0718,2024-04-12,trending,0.771,False,16,Mobile,evening,v1.2
4,rec_000005,user_06794,movie_0718,2025-10-30,similar_users,0.251,False,9,Tablet,evening,v1.3
5,rec_000006,user_03345,movie_0346,2024-09-01,personalized,0.975,False,13,Smart TV,morning,v2.0
6,rec_000007,user_01519,movie_0264,2024-06-28,similar_users,0.722,False,20,Mobile,night,v1.2
7,rec_000008,user_03328,movie_0385,2024-10-09,personalized,0.755,False,11,Tablet,night,v1.4
8,rec_000009,user_04944,movie_0957,2025-11-13,new_releases,0.590,False,14,Tablet,night,v1.4
9,rec_000010,user_07953,movie_0815,2025-02-08,personalized,NaN,False,13,Tablet,morning,v1.4

In [11]:
reviews = pd.read_csv('DataSets/reviews.csv')
reviews.head(10)

,review_id,user_id,movie_id,rating,review_date,device_type,is_verified_watch,helpful_votes,total_votes,review_text,sentiment,sentiment_score
0,review_000001,user_07066,movie_0360,4,2025-03-29,Mobile,False,3.0,5.0,Fantastic cinematography and plot twists.,positive,0.711
1,review_000002,user_02953,movie_0095,5,2024-07-19,Mobile,True,2.0,2.0,This series is a masterpiece!,positive,0.645
2,review_000003,user_05528,movie_0518,4,2025-02-11,Tablet,True,2.0,5.0,Fantastic cinematography and plot twists.,positive,0.730
3,review_000004,user_07612,movie_0672,5,2025-11-26,Mobile,True,7.0,7.0,One of the best series I've ever watched. High...,positive,0.798
4,review_000005,user_03424,movie_0580,3,2025-07-11,Mobile,True,1.0,5.0,Mixed feelings about this one.,neutral,0.410
5,review_000006,user_07263,movie_0708,3,2025-01-06,Tablet,True,4.0,5.0,Okay for a one-time watch.,neutral,NaN
6,review_000007,user_07818,movie_0081,2,2025-01-18,Smart TV,True,4.0,7.0,Not worth the time. Very predictable.,negative,0.106
7,review_000008,user_03744,movie_0526,1,2025-09-26,Smart TV,True,1.0,4.0,NaN,negative,0.251
8,review_000009,user_04454,movie_0551,4,2024-02-02,Mobile,True,1.0,5.0,This movie exceeded my expectations.,positive,0.737
9,review_000010,user_02897,movie_0800,3,2025-03-22,Tablet,True,5.0,10.0,Could have been better.,neutral,0.451

In [12]:
search_logs = pd.read_csv('DataSets/search_logs.csv')
search_logs.head(10)

,search_id,user_id,search_query,search_date,results_returned,clicked_result_position,device_type,search_duration_seconds,had_typo,used_filters,location_country
0,search_000001,user_09864,classic movies,2024-03-22,20,2.0,Tablet,12.4,False,False,Canada
1,search_000002,user_08038,stand up comedy,2025-11-22,24,4.0,Tablet,63.5,True,False,USA
2,search_000003,user_02009,music documentaries,2024-10-09,86,1.0,Tablet,24.7,True,False,USA
3,search_000004,user_01083,comedy shows,2024-12-14,70,4.0,Mobile,53.7,False,False,USA
4,search_000005,user_04269,movies based on true stories,2025-01-10,48,NaN,Tablet,69.6,True,False,USA
5,search_000006,user_03478,thriller series,2024-09-18,76,4.0,Laptop,7.2,False,True,USA
6,search_000007,user_03800,travel documentaries,2025-10-03,70,NaN,Laptop,12.3,False,False,USA
7,search_000008,user_00191,superhero movies,2024-05-24,50,1.0,Laptop,17.4,False,True,USA
8,search_000009,user_03999,biographies,2025-07-18,7,NaN,Laptop,7.0,False,False,USA
9,search_000010,user_06785,movies based on true stories,2025-04-09,31,NaN,Smart TV,20.2,False,False,Canada

In [14]:
users = pd.read_csv('DataSets/users.csv')
users.head(10)

,user_id,email,first_name,last_name,age,gender,country,state_province,city,subscription_plan,subscription_start_date,is_active,monthly_spend,primary_device,household_size,created_at
0,user_00001,figueroajohn@example.org,Erica,Garza,43.0,Male,USA,Massachusetts,North Jefferyhaven,Basic,2024-04-08,True,36.06,Laptop,1.0,2023-04-01 14:40:50.540242
1,user_00002,blakeerik@example.com,Joshua,Bernard,38.0,Male,USA,Texas,North Noahstad,Premium+,2024-05-24,True,14.59,Desktop,2.0,2024-10-10 15:39:11.030515
2,user_00003,smiller@example.net,Barbara,Williams,32.0,Female,USA,Michigan,Traciebury,Standard,2023-09-22,False,11.71,Desktop,3.0,2024-06-29 14:27:49.560875
3,user_00004,mitchellclark@example.com,Chelsea,Ferguson,11.0,Male,USA,Ohio,South Noah,Standard,2024-08-21,True,28.56,Laptop,2.0,2023-04-11 01:01:59.614841
4,user_00005,richard13@example.net,Jason,Foster,21.0,Female,USA,Arizona,West Donald,Standard,2024-10-28,True,9.54,Desktop,6.0,2025-04-12 19:59:30.137806
5,user_00006,jeffrey28@example.com,Katelyn,Hernandez,43.0,Female,Canada,Quebec,Carlsonfurt,Standard,2024-05-16,True,NaN,Gaming Console,2.0,2024-03-04 19:57:36.106319
6,user_00007,maldonadoamanda@example.com,Daniel,Moore,63.0,NaN,USA,Maryland,Teresaburgh,Premium,2025-03-13,True,27.74,Desktop,1.0,2025-02-10 07:18:23.258712
7,user_00008,nathanielmartin@example.net,Carol,Smith,NaN,Male,Canada,New Brunswick,Johnbury,Basic,2022-11-03,True,6.69,Tablet,1.0,2025-01-13 04:53:02.134116
8,user_00009,donnaarroyo@example.org,Allison,Brandt,24.0,Male,USA,North Carolina,Raymondstad,Premium,2025-04-13,True,12.21,Gaming Console,5.0,2022-12-13 15:46:23.391721
9,user_00010,morganbrianna@example.org,Adrian,Perez,24.0,Male,USA,Pennsylvania,Chadbury,Basic,2024-08-04,True,23.18,Laptop,1.0,2024-03-15 22:04:39.445799

In [15]:
watch_history = pd.read_csv('DataSets/watch_history.csv')
watch_history.head(10)

,session_id,user_id,movie_id,watch_date,device_type,watch_duration_minutes,progress_percentage,action,quality,location_country,is_download,user_rating
0,session_000001,user_07271,movie_0511,2025-11-13,Tablet,63.9,34.6,completed,HD,USA,False,NaN
1,session_000002,user_00861,movie_0588,2025-02-26,Laptop,120.1,44.2,started,HD,USA,False,NaN
2,session_000003,user_05391,movie_0694,2024-12-15,Desktop,572.1,84.7,started,HD,Canada,False,1.0
3,session_000004,user_05192,movie_0234,2024-09-30,Desktop,395.3,89.9,completed,SD,USA,False,5.0
4,session_000005,user_05735,movie_0390,2024-08-04,Tablet,14.6,6.2,completed,HD,USA,False,NaN
5,session_000006,user_06266,movie_0631,2024-03-13,Desktop,43.4,63.7,completed,HD,Canada,False,NaN
6,session_000007,user_00467,movie_0483,2025-04-23,Desktop,165.9,63.1,stopped,HD,Canada,False,NaN
7,session_000008,user_04427,movie_0139,2025-09-13,Laptop,100.4,57.4,paused,4K,USA,False,NaN
8,session_000009,user_05579,movie_0769,2025-08-26,Laptop,29.0,9.8,paused,4K,USA,False,NaN
9,session_000010,user_08323,movie_0577,2025-07-23,Desktop,32.5,74.1,stopped,HD,USA,False,NaN

TESTING TESTING